### ISSUE TITLE
Asking for bi-encoder models

### ISSUE THREAD

**Issue by eeehco** [Danield21/Rationale4CDECR#2]
When I run generated_pairs.py separately with ’python -u src/all_models/generated_pairs.py --config_path configs/retrieved_data/pair_generation.json --dataset ecb --data_split train --out_dir retrieved_data/main‘, an error message will appear as follows: "FileNotFoundError: [Errno 2] No such file or directory: './models/ecb_events_seed5_original/candidate_generator_best_model'".
May I ask if you can provide this model file?

**Comment by Danield21** [comment]
Hi, thanks for your attention. 

This code repository is still under maintenance. We will continue to upload some codes and interpretations. Compared to before, we have made some adjustments to the file layout and some codes in the repo, and we provide links to trained bi-encoder [models]( https://drive.google.com/file/d/15G_AxNPDvy90eKXookS7EWrdjr8VhF6E/view?usp=drive_link) and retrieved/enhanced pairwise [dataset](https://drive.google.com/file/d/1TSDVho-CXByavWox4dT8cxWO-gn6fFpR/view?usp=drive_link) in [data_preparation](https://github.com/Danield21/Rationale4CDECR/tree/main/data_preparation). Please stay tuned for our latest version. 

The core code of generated_pairs.py is based on [Held's code](https://github.com/Helw150/event_entity_coref_ecb_plus/blob/master/src/all_models/nearest_neighbor.py#L173). You are free to use it to generate data pairs on your own. However, we observe that it still has some indeterminacy so it may yield slightly different pairwise datasets. For more valid and deterministic experiments, we recommend using our fixed training set from the retrieved_data folder which can be downloaded from the provided link.

Best,
Daniel

**Comment by eeehco** [comment]
> Hi, thanks for your attention.
> 
> This code repository is still under maintenance. We will continue to upload some codes and interpretations. Compared to before, we have made some adjustments to the file layout and some codes in the repo, and we provide links to trained bi-encoder [models](https://drive.google.com/file/d/15G_AxNPDvy90eKXookS7EWrdjr8VhF6E/view?usp=drive_link) and retrieved/enhanced pairwise [dataset](https://drive.google.com/file/d/1TSDVho-CXByavWox4dT8cxWO-gn6fFpR/view?usp=drive_link) in [data_preparation](https://github.com/Danield21/Rationale4CDECR/tree/main/data_preparation). Please stay tuned for our latest version.
> 
> The core code of generated_pairs.py is based on [Held's code](https://github.com/Helw150/event_entity_coref_ecb_plus/blob/master/src/all_models/nearest_neighbor.py#L173). You are free to use it to generate data pairs on your own. However, we observe that it still has some indeterminacy so it may yield slightly different pairwise datasets. For more valid and deterministic experiments, we recommend using our fixed training set from the retrieved_data folder which can be downloaded from the provided link.
> 
> Best, Daniel

Thanks for your reply.The model can train now.
![image](https://github.com/Danield21/Rationale4CDECR/assets/102967148/1bfe113b-9847-4a84-86a1-57667bb7d7f8)

**Comment by eeehco** [comment]
> Hi, thanks for your attention.
> 
> This code repository is still under maintenance. We will continue to upload some codes and interpretations. Compared to before, we have made some adjustments to the file layout and some codes in the repo, and we provide links to trained bi-encoder [models](https://drive.google.com/file/d/15G_AxNPDvy90eKXookS7EWrdjr8VhF6E/view?usp=drive_link) and retrieved/enhanced pairwise [dataset](https://drive.google.com/file/d/1TSDVho-CXByavWox4dT8cxWO-gn6fFpR/view?usp=drive_link) in [data_preparation](https://github.com/Danield21/Rationale4CDECR/tree/main/data_preparation). Please stay tuned for our latest version.
> 
> The core code of generated_pairs.py is based on [Held's code](https://github.com/Helw150/event_entity_coref_ecb_plus/blob/master/src/all_models/nearest_neighbor.py#L173). You are free to use it to generate data pairs on your own. However, we observe that it still has some indeterminacy so it may yield slightly different pairwise datasets. For more valid and deterministic experiments, we recommend using our fixed training set from the retrieved_data folder which can be downloaded from the provided link.
> 
> Best, Daniel

May I ask if your training code (Python - u src/all_models/crossencoder_trainer. py) is also so slow?

**Comment by Danield21** [comment]
> > Hi, thanks for your attention.
> > This code repository is still under maintenance. We will continue to upload some codes and interpretations. Compared to before, we have made some adjustments to the file layout and some codes in the repo, and we provide links to trained bi-encoder [models](https://drive.google.com/file/d/15G_AxNPDvy90eKXookS7EWrdjr8VhF6E/view?usp=drive_link) and retrieved/enhanced pairwise [dataset](https://drive.google.com/file/d/1TSDVho-CXByavWox4dT8cxWO-gn6fFpR/view?usp=drive_link) in [data_preparation](https://github.com/Danield21/Rationale4CDECR/tree/main/data_preparation). Please stay tuned for our latest version.
> > The core code of generated_pairs.py is based on [Held's code](https://github.com/Helw150/event_entity_coref_ecb_plus/blob/master/src/all_models/nearest_neighbor.py#L173). You are free to use it to generate data pairs on your own. However, we observe that it still has some indeterminacy so it may yield slightly different pairwise datasets. For more valid and deterministic experiments, we recommend using our fixed training set from the retrieved_data folder which can be downloaded from the provided link.
> > Best, Daniel
> 
> May I ask if your training code (Python - u src/all_models/crossencoder_trainer. py) is also so slow?

Our experiments were on a single Nvidia Tesla V100. The training will take around a day for the baseline model, and around two days for the enhanced model on ECB+.

**Comment by eeehco** [comment]
> > > Hi, thanks for your attention.
> > > This code repository is still under maintenance. We will continue to upload some codes and interpretations. Compared to before, we have made some adjustments to the file layout and some codes in the repo, and we provide links to trained bi-encoder [models](https://drive.google.com/file/d/15G_AxNPDvy90eKXookS7EWrdjr8VhF6E/view?usp=drive_link) and retrieved/enhanced pairwise [dataset](https://drive.google.com/file/d/1TSDVho-CXByavWox4dT8cxWO-gn6fFpR/view?usp=drive_link) in [data_preparation](https://github.com/Danield21/Rationale4CDECR/tree/main/data_preparation). Please stay tuned for our latest version.
> > > The core code of generated_pairs.py is based on [Held's code](https://github.com/Helw150/event_entity_coref_ecb_plus/blob/master/src/all_models/nearest_neighbor.py#L173). You are free to use it to generate data pairs on your own. However, we observe that it still has some indeterminacy so it may yield slightly different pairwise datasets. For more valid and deterministic experiments, we recommend using our fixed training set from the retrieved_data folder which can be downloaded from the provided link.
> > > Best, Daniel
> > 
> > 
> > May I ask if your training code (Python - u src/all_models/crossencoder_trainer. py) is also so slow?
> 
> Our experiments were on a single Nvidia Tesla V100. The training will take around a day for the baseline model, and around two days for the enhanced model on ECB+.

Thanks for your reply. I use an A100, which looks similar and takes about eight hours for the baseline model on ECB+.
