### ISSUE TITLE
something about evaluation results

### ISSUE THREAD

**Issue by eeehco** [Danield21/Rationale4CDECR#3]
May I ask if F1 in the evaluation results refers to CoNLL F1：
![image](https://github.com/user-attachments/assets/7089acc2-0a36-4656-aab1-336d21ff0cbc)

**Comment by eeehco** [comment]
> May I ask if F1 in the evaluation results refers to CoNLL F1： ![image](https://private-user-images.githubusercontent.com/102967148/348591062-7089acc2-0a36-4656-aab1-336d21ff0cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjU3MTIsIm5iZiI6MTcyMTAyNTQxMiwicGF0aCI6Ii8xMDI5NjcxNDgvMzQ4NTkxMDYyLTcwODlhY2MyLTBhMzYtNDY1Ni1hYWIxLTMzNmQyMWZmMGNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNjM2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjJhMDcyNDQ1YjU5NmRjMjk4ZTQxMmNiOGJmNDI0NTZjYTUwNDgwZDQzMzM1YmRkZjJkYmY0NjEzNmVlYjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aqm3hC4u8Snmw_MuJuPBr5W2L1uy3vIjld9pNner-H0)

It seems to refer to B3. How can I use CoNLL's official evaluation script to evaluate other indicators, such as muc. How can I obtain the CoNLL official evaluation script, which requires a model predicted co index chain and a real co index chain?

**Comment by eeehco** [comment]
> > May I ask if F1 in the evaluation results refers to CoNLL F1： ![image](https://private-user-images.githubusercontent.com/102967148/348591062-7089acc2-0a36-4656-aab1-336d21ff0cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjU3MTIsIm5iZiI6MTcyMTAyNTQxMiwicGF0aCI6Ii8xMDI5NjcxNDgvMzQ4NTkxMDYyLTcwODlhY2MyLTBhMzYtNDY1Ni1hYWIxLTMzNmQyMWZmMGNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNjM2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjJhMDcyNDQ1YjU5NmRjMjk4ZTQxMmNiOGJmNDI0NTZjYTUwNDgwZDQzMzM1YmRkZjJkYmY0NjEzNmVlYjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aqm3hC4u8Snmw_MuJuPBr5W2L1uy3vIjld9pNner-H0)
> 
> It seems to refer to B3. How can I use CoNLL's official evaluation script to evaluate other indicators, such as muc. How can I obtain the CoNLL official evaluation script, which requires a model predicted co index chain and a real co index chain?

I need to calculate the F1 value of Conll, including the F1 values of MUC, B3, and CEAFE. Can you tell me how to calculate it？

**Comment by Danield21** [comment]
You can refer to https://github.com/Danield21/Rationale4CDECR/blob/main/conll_eval/coreference_eval.ipynb

**Comment by eeehco** [comment]
> You can refer to https://github.com/Danield21/Rationale4CDECR/blob/main/conll_eval/coreference_eval.ipynb

Thanks! It worked.
