### ISSUE TITLE
Some questions about the results

### ISSUE THREAD

**Issue by era211** [Danield21/Rationale4CDECR#4]
Hello author, when I was replicating the code, I found that the results of the first epoch were good, and since the second epoch, the results of each epoch have remained the same.May I ask why this is?
![image](https://github.com/user-attachments/assets/b59221fe-8d2d-4e1a-86cc-2311402d0442)

**Comment by Danield21** [comment]
Hi, the results look definately very weird. I have uploaded all of my training log in [outputs](https://github.com/Danield21/Rationale4CDECR/tree/main/outputs/main) which are normal.   
Did you strictly use the code and config in the repo without any modification?  Could you please tell me the code and config you used for such result?

**Comment by era211** [comment]
> Hi, the results look definately very weird. I have uploaded all of my training log in [outputs](https://github.com/Danield21/Rationale4CDECR/tree/main/outputs/main) which are normal. Did you strictly use the code and config in the repo without any modification? Could you please tell me the code and config you used for such result?

it's ok
